version: '3.1'

services:

  production-nginx-container:
    container_name: 'production-nginx-container'
    restart: always
    image: nginx:1.14.0
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./certificates/fullchain.pem:/etc/certificates/fullchain.pem
      - ./certificates/privkey.pem:/etc/certificates/privkey.pem
